'use strict';

exports.PODS = 'PODS';
exports.DEPENDENCIES = 'DEPENDENCIES';
exports.SPEC_REPOS = 'SPEC REPOS';
exports.SPEC_CHECKSUMS = 'SPEC CHECKSUMS';
exports.EXTERNAL_SOURCES = 'EXTERNAL SOURCES';
exports.CHECKOUT_OPTIONS = 'CHECKOUT OPTIONS';
exports.PODFILE_CHECKSUM = 'PODFILE CHECKSUM';
exports.COCOAPODS = 'COCOAPODS';

